from flask import Flask, abort, flash, render_template, request, redirect, url_for
import psycopg2
import psycopg2.extras
import psycopg2.errors
import os
from werkzeug.utils import secure_filename
from datetime import datetime

app = Flask(__name__)

app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "estoque-dev-key")

UPLOAD_FOLDER = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "static",
    "images"
)

app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
database_initialized = False


def get_db():
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        raise RuntimeError("A variável DATABASE_URL não foi configurada.")

    conn = psycopg2.connect(database_url, connect_timeout=10)
    return conn


def get_cursor(conn):
    return conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)


def init_db():
    conn = get_db()
    cursor = get_cursor(conn)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS produtos (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome TEXT NOT NULL UNIQUE,
            imagem TEXT,
            quantidade INTEGER NOT NULL DEFAULT 0
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS movimentos (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            produto_id BIGINT NOT NULL,
            tipo TEXT NOT NULL CHECK(tipo IN ('entrada', 'saida')),
            quantidade INTEGER NOT NULL,
            data TEXT NOT NULL,
            FOREIGN KEY (produto_id) REFERENCES produtos(id)
        )
    """)

    produtos_iniciais = [
        ("Coca-Cola", "coca_cola.png"),
        ("Pepsi", "pepsi.png"),
        ("Fanta", "fanta.png"),
    ]

    for nome, imagem in produtos_iniciais:
        cursor.execute(
            """
            INSERT INTO produtos (nome, imagem, quantidade)
            VALUES (%s, %s, 0)
            ON CONFLICT (nome) DO NOTHING
            """,
            (nome, imagem)
        )

        cursor.execute(
            """
            UPDATE produtos
            SET imagem = %s
            WHERE nome = %s
            AND (imagem IS NULL OR imagem = '')
            """,
            (imagem, nome)
        )

    conn.commit()
    cursor.close()
    conn.close()


@app.before_request
def ensure_database():
    global database_initialized
    if not database_initialized:
        init_db()
        database_initialized = True


def allowed_image(filename):
    allowed_extensions = {"png", "jpg", "jpeg", "gif", "webp"}

    return (
        "." in filename
        and filename.rsplit(".", 1)[1].lower() in allowed_extensions
    )


@app.route("/")
def index():
    conn = get_db()
    cursor = get_cursor(conn)

    cursor.execute("SELECT * FROM produtos ORDER BY nome")
    produtos = cursor.fetchall()

    cursor.execute("SELECT COUNT(*) AS total FROM produtos")
    total_produtos = cursor.fetchone()["total"]

    cursor.execute("""
        SELECT COALESCE(SUM(quantidade), 0) AS total
        FROM produtos
    """)
    estoque_total = cursor.fetchone()["total"]

    cursor.execute("""
        SELECT COUNT(*) AS total
        FROM movimentos
        WHERE tipo = 'entrada'
    """)
    total_entradas = cursor.fetchone()["total"]

    cursor.execute("""
        SELECT COUNT(*) AS total
        FROM movimentos
        WHERE tipo = 'saida'
    """)
    total_saidas = cursor.fetchone()["total"]

    cursor.close()
    conn.close()

    return render_template(
        "index.html",
        produtos=produtos,
        total_produtos=total_produtos,
        estoque_total=estoque_total,
        total_entradas=total_entradas,
        total_saidas=total_saidas,
    )


@app.route("/movimentar", methods=["POST"])
def movimentar():
    produto_id = request.form.get("produto_id")
    tipo = request.form.get("tipo")

    if not produto_id:
        abort(400)

    try:
        quantidade = int(request.form["quantidade"])
    except (KeyError, TypeError, ValueError):
        flash("Informe uma quantidade válida.", "erro")
        return redirect(url_for("index"))

    if quantidade < 1 or tipo not in {"entrada", "saida"}:
        flash("A quantidade deve ser maior que zero.", "erro")
        return redirect(url_for("index"))

    conn = get_db()
    cursor = get_cursor(conn)

    cursor.execute(
        "SELECT * FROM produtos WHERE id = %s",
        (produto_id,)
    )

    produto = cursor.fetchone()

    if produto is None:
        cursor.close()
        conn.close()
        abort(404)

    if tipo == "entrada":
        nova_quantidade = produto["quantidade"] + quantidade

    else:
        if quantidade > produto["quantidade"]:
            cursor.close()
            conn.close()

            flash(
                "A saída não pode ser maior que o estoque disponível.",
                "erro"
            )

            return redirect(url_for("index"))

        nova_quantidade = produto["quantidade"] - quantidade

    cursor.execute(
        """
        UPDATE produtos
        SET quantidade = %s
        WHERE id = %s
        """,
        (nova_quantidade, produto_id)
    )

    cursor.execute(
        """
        INSERT INTO movimentos
        (produto_id, tipo, quantidade, data)
        VALUES (%s, %s, %s, %s)
        """,
        (
            produto_id,
            tipo,
            quantidade,
            datetime.now().strftime("%d/%m/%Y %H:%M")
        )
    )

    conn.commit()

    cursor.close()
    conn.close()

    return redirect(url_for("index"))


@app.route("/produto/novo", methods=["GET", "POST"])
def novo_produto():

    if request.method == "POST":

        nome = request.form.get("nome", "").strip()

        if not nome:
            flash("Informe o nome do produto.", "erro")
            return render_template("add_product.html"), 400

        imagem_file = request.files.get("imagem")
        nome_arquivo = None

        if imagem_file and imagem_file.filename:

            if not allowed_image(imagem_file.filename):
                flash(
                    "Envie uma imagem PNG, JPG, JPEG, GIF ou WEBP.",
                    "erro"
                )

                return render_template("add_product.html"), 400

            nome_arquivo = secure_filename(imagem_file.filename)

            imagem_file.save(
                os.path.join(
                    app.config["UPLOAD_FOLDER"],
                    nome_arquivo
                )
            )

        conn = get_db()
        cursor = get_cursor(conn)

        try:

            cursor.execute(
                """
                INSERT INTO produtos
                (nome, imagem, quantidade)
                VALUES (%s, %s, 0)
                """,
                (nome, nome_arquivo)
            )

            conn.commit()

        except psycopg2.errors.UniqueViolation:

            conn.rollback()
            cursor.close()
            conn.close()

            flash(
                "Já existe um produto com esse nome.",
                "erro"
            )

            return render_template(
                "add_product.html"
            ), 400

        cursor.close()
        conn.close()

        return redirect(url_for("index"))

    return render_template("add_product.html")


@app.route("/historico/<int:produto_id>")
def historico(produto_id):

    conn = get_db()
    cursor = get_cursor(conn)

    cursor.execute(
        "SELECT * FROM produtos WHERE id = %s",
        (produto_id,)
    )

    produto = cursor.fetchone()

    if produto is None:
        cursor.close()
        conn.close()
        abort(404)

    cursor.execute(
        """
        SELECT *
        FROM movimentos
        WHERE produto_id = %s
        ORDER BY id DESC
        """,
        (produto_id,)
    )

    movimentos = cursor.fetchall()
    cursor.close()
    conn.close()
    return render_template("historico.html", produto=produto, movimentos=movimentos)


@app.route("/historico/limpar", methods=["POST"])
def limpar_historico():
    conn = get_db()
    cursor = get_cursor(conn)
    try:
        cursor.execute("DELETE FROM movimentos")
        conn.commit()
    finally:
        cursor.close()
        conn.close()
    return redirect(url_for("index"))


if __name__ == "__main__":
    init_db()
    app.run(debug=True)